repos:
  # Ruff - Ultra-fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Additional Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.csv$' # Exclude CSV files from trailing whitespace checks
      - id: end-of-file-fixer
        exclude: '\.csv$' # Exclude CSV files
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: 'data/.*\.json$' # Exclude data files from JSON checks
      - id: check-added-large-files
        args: ["--maxkb=1000"] # Allow files up to 1MB
      - id: check-merge-conflict
      - id: debug-statements

  # MyPy static type checking (relaxed for this project)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args:
          [
            --ignore-missing-imports,
            --no-strict-optional,
            --disable-error-code=import-untyped,
          ]
        additional_dependencies:
          - types-requests
          - pandas-stubs

  # Security scanning with bandit (relaxed)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [--skip, B101, B602, B603, B301] # Skip common issues for data scripts
        exclude: "data/.*" # Exclude data files from security scanning

  # YAML formatting (only for workflow files)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.ya?ml$
        exclude: '^(\.ai-assistant/|data/)'

  # Secrets detection (optional - requires detect-secrets installation)
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.4.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.secrets.baseline']
